@extends('errors.deels')
@section('title','Страница не найдена')
@section('code','404')
@section('heading','Такой страницы нет')
@section('message','Возможно, ссылка изменилась, челлендж завершён или контент больше недоступен.')
